### ISSUE TITLE
Index Out Of Range Error in Stat.init

### ISSUE THREAD

**Issue by WillScott73** [Verizon/AcUtils#1]
This code goes pop in stat.init if there is no Virtual value in the xml being parsed.

                string vir = (string)e.Attribute("Virtual") ?? String.Empty;
                    string[] arrVir = vir.Split('\\');
                    int ival;
                    if (Int32.TryParse(arrVir[0], NumberStyles.Integer, null, out ival))
                        element.VirStreamNumber = ival;
                    if (Int32.TryParse(arrVir[1], NumberStyles.Integer, null, out ival))
                        element.VirVersionNumber = ival;

There is no Virtual value when you do stat -x -foix to get a list of external elements. Clearly you check to see if Virtual was present and set a empty string if not, but then don't check before parsing.

**Comment by bbuttolph** [comment]
@WillScott73 sorry for not leaving a reply earlier. This was my first (only!) issue on GitHub and I missed seeing the reply box. As you probably noticed, I applied the fix. Thank you for reporting it.
